-- Ejecutar una sola vez en Supabase > SQL Editor
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  created_at timestamptz default now()
);

alter table public.gallery enable row level security;

drop policy if exists "Galeria lectura publica" on public.gallery;
create policy "Galeria lectura publica" on public.gallery
for select using (true);

drop policy if exists "Galeria insertar autenticados" on public.gallery;
create policy "Galeria insertar autenticados" on public.gallery
for insert to authenticated with check (true);

drop policy if exists "Galeria borrar autenticados" on public.gallery;
create policy "Galeria borrar autenticados" on public.gallery
for delete to authenticated using (true);

insert into storage.buckets (id,name,public)
values ('gallery-images','gallery-images',true)
on conflict (id) do update set public=true;

drop policy if exists "Galeria storage lectura" on storage.objects;
create policy "Galeria storage lectura" on storage.objects
for select using (bucket_id='gallery-images');

drop policy if exists "Galeria storage subir" on storage.objects;
create policy "Galeria storage subir" on storage.objects
for insert to authenticated with check (bucket_id='gallery-images');

alter table public.gallery
add column if not exists gallery_tag text,
add column if not exists note text;
