<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Noticia · PSA Valencia 2026</title>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow:wght@400;600;700&family=Barlow+Condensed:wght@600;700;800&display=swap" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.45.4/dist/umd/supabase.min.js"></script>
<style>*{box-sizing:border-box}body{margin:0;background:#001b2d;color:#dceaf4;font-family:Barlow,Arial,sans-serif}.wrap{max-width:900px;margin:auto;padding:30px 22px}header{background:#000f1a;padding:18px 0}a{color:inherit;text-decoration:none}.logo{font:800 22px 'Barlow Condensed';color:#fff}article{padding:45px 0 80px}h1{font:400 clamp(46px,8vw,82px)/.95 'Bebas Neue';color:#fff;margin:10px 0 20px}.date{color:#ff7900;font-weight:700;text-transform:uppercase}.heroimg{width:100%;max-height:560px;object-fit:cover;margin:20px 0 30px}.text{font-size:19px;line-height:1.8;color:#c1d0d9;white-space:pre-line}.back{display:inline-block;background:#ff7900;color:#001b2d;padding:12px 20px;font-weight:800;margin-top:30px}</style>
</head><body><header><div class="wrap"><a class="logo" href="index.html">← PSA VALENCIA 2026</a></div></header><main class="wrap"><article id="article">Cargando noticia...</article></main>
<script>
const client=supabase.createClient("https://texjzaanugmssmolzwgb.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleGp6YWFudWdtc3Ntb2x6d2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0NzU5MDYsImV4cCI6MjEwMDA1MTkwNn0.L36iUvzMeZnLfT-3sqXzjPFJ_S_of20ATi1_QKKxWGo");
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
(async()=>{const id=new URLSearchParams(location.search).get('id');if(!id){article.textContent='Noticia no encontrada.';return}
const {data,error}=await client.from('news').select('*').eq('id',id).single();if(error||!data){article.textContent='Noticia no encontrada.';return}
const lang=(new URLSearchParams(location.search).get('lang')||localStorage.getItem('psav_lang')||'es').slice(0,2);const title=data['title_'+lang]||data.title_es||data.title||'';const description=data['description_'+lang]||data.description_es||data.description||'';const back=lang==='va'?'TORNAR A NOTÍCIES':lang==='en'?'BACK TO NEWS':lang==='fr'?'RETOUR AUX ACTUALITÉS':'VOLVER A NOTICIAS';document.title=title+' · PSA Valencia 2026';article.innerHTML=`<div class="date">${new Date(data.news_date+'T12:00:00').toLocaleDateString(lang,{day:'2-digit',month:'long',year:'numeric'})}</div><h1>${esc(title)}</h1>${data.image_url?`<img class="heroimg" src="${data.image_url}" alt="">`:''}<div class="text">${esc(description)}</div><a class="back" href="index.html#news">${back}</a>`;})();
</script></body></html>